<?php $fieldcounts = count($this->fildnames) + 1; ?>
<div class="contentPanel">

    <div class="zf-table-wrap  form-inline">

        <div class="row ">
            <div class="col-sm-6 pull-left">
                <header>
                    <h3 class="orange">Manage TDR Rate</h3>
                </header>
            </div>
            <div class="col-sm-6 pull-right"> 
                <div class="addUserBtn"><a href="<?php echo $this->url('admin/default', array('controller' => 'finance', 'action' => 'tdrrateadd')); ?>">Add TDR Rate</a></div>
            </div>

        </div>
        <div class="addUserTitleStrip">
            <h4>TDR List</h4>
        </div>

    </div>
      <?php if(!empty($datas)){?>
    <div id="tableContainer">
        <table id="tdrrate" class="display table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr class="dataTable-title">
                    <th>Sr. No</th>
                    <?php
                    for ($j = 0; count($fildnames) > $j; $j++) {
                        $fieldnameval = $fildnames[$j];
                        echo "<th>$fieldnameval</th>";
                    }
                    ?>
                    <th>Action
                    </th>
                </tr>
            </thead>



        </table>
    </div>
 <?php }else{?>
    <div id="tableContainer" class="dataTable-title nodata">
       Empty Record Found!
    </div>
    <?php  } ?>
</div>            

<script type="text/javascript">
    $(document).ready(function () {
        $('body').click(function () {

            $('#popup_box').fadeOut("slow");
            $(".commonPopupContainerDiv").css({"display": "none"});
            $(".commonPopupContainerDiv").css({"opacity": "1"});
        });


        var td = $('#tdrrate').DataTable({
            stateSave: true,
            responsive: true,
            dom: 'C<"clear">lfrtip',
            colVis: {
                activate: "mouseover",
                exclude: [0, 1,<?php echo $fieldcounts; ?>]
            },
            "ajax": {
                "url": "/admin/finance/ajaxtdrrate",
                "dataSrc": "data"
            },
            "columnDefs": [{
                    "targets": -1,
                    "data": null,
                    "render": function (data, type, full, meta) {
                        var dataval = "/admin/finance/tdrrateedit/" + data[1];
                        return '<span class="userEditOptionsDiv"><span class="userEditOptionsPopup"><a class="popup" id="' + data[1] + '" href="javascript:void(0)"><span class="userEditOptionTxt">View paymentgatway</span></a><a href="' + dataval + '"><span class="userEditOptionTxt">Modify PaymentGateway</span></a><a  href="javascript:void(0)" ><span class="userEditOptionTxt status"  id="' + data[1] + '">Change Status</span></a></span></span>';
                    },
                    // "defaultContent": "<span class='userEditOptionsDiv'><span class='userEditOptionsPopup'><span class='userEditOptionTxt'><a href='/admin/user/subuseredit/%s'>Modify Sub User</a></span><span class='userEditOptionTxt status'  id='%s'><a  href='javascript:void(0)' >Change Status</a></span></span></span>" ,
                    "orderable": false
                },
                {
                    "targets": 4,
                    "data": null,
                    "render": function (data, type, full, meta) {
                        if (data[4] == "1")
                        {
                            return '<span class="label label-success">Active</span>';
                        }
                        else
                        {
                            return '<span class="label label-warning">Inactive</span>';
                        }
                    },
                },
                {
                    "targets": [1],
                    "visible": false
                }, {
                    "searchable": false,
                    "orderable": false,
                    "targets": 0
                }],
            "order": [[1, 'desc']]

        });
        td.on('order.dt search.dt', function () {
            td.column(0, {search: 'applied', order: 'applied'}).nodes().each(function (cell, i) {
                cell.innerHTML = i + 1;
            });
        }).draw();
        td.on('order.dt search.dt', function () {
            $(".userEditOptionsDiv").hover(function () {
                $(this).children('.userEditOptionsPopup').show();
            }, function () {
                $(this).children('.userEditOptionsPopup').hide();
            });
        }).draw();
        td.on('order.dt search.dt', function () {
            $('.popup').click(function () {
                // alert('okoko');

                //   var get  =  $('div.inneraction').children('a.popup').attr('id')(); 
                //var get  =   $('span#cool a.popup').eq(1).attr('id');
                // var get  =   $(this).attr('id');
                // alert(get);
                var getviewValue = $(this).attr('id');
                ;
                // alert(getviewValue);
                var myData = {textgetviewValueData: getviewValue};
                $.ajax({
                    type: "POST",
                    url: "/admin/finance/tdrrateview",
                    data: myData,
                    dataType: "JSON",
                    success: function (data) {
                        var arr23 = $.map(data[0], function (i, el) {
                            return el + "-" + i;
                        })
                        $('#popup_box').fadeIn("fast");
                        $(".commonPopupContainerDiv").css({"display": "block"});
                        $(".commonPopupContainerDiv").css({"opacity": "0.8"});
                        var html = '<div class="commonPopupClose"></div><div class="commonPopupContentDiv">';
                        for (var i = 0; i < arr23.length; i++) {
                            var submod = arr23[i].split("-");
                            //var fieldnameval=submod[0].replaceAll('_', ' ');
                            var fieldnameval = submod[0].replace(/_/g, " ");
                            html = html + '<div class="commonPopupLabel">' + fieldnameval + '</div><div class="commonPopupValue">' + submod[1] + '</div>';
                        }
                        html = html + '</div>';
                        $('#popup_box').html(
                                html
                                );
                    },
                    failure: (
                            function ()
                            {
                                alert("Failure!!");
                            }
                    )


                });
            });
        }).draw();

        td.on('order.dt search.dt', function () {

         
            $(".status").click(function () {
                var yes = confirm('Are you sure that you want to Change the item?');

                if (yes)
                {
                    var getValue = this.id;
                    var myData = {textData: getValue, type: "Ftdrrate"};
                    $.ajax({
                        type: "POST",
                        url: "/admin/finance/changestatus", // call to Action method in COntroller 
                        data: myData,
                        dataType: "JSON",
                        success: function (data) {
                                    td.ajax.reload( null, false);
                        },
                        failure: (function () {
                            alert("Failure!!");
                        })
                    });
                }

            });
        }).draw();
    });
</script>
<style>

    .actiontooltip
    {
        position:absolute;
        width: 140px;
        text-align: center;


    }     
    .inneraction {
        border-bottom: 2px solid #c1c1c1;
        position:relative;
        bottom: 5px;
        left: 5px;
        height: auto;
        width: 110px;
        background:#fff;
        color: #FFFFFF;
        display:none;
        text-shadow: none;
        z-index: 1000;
        padding: 20px;
        line-height: 19px;
        text-align: justify;
        opacity: 0.8;
    }
</style>

<script type="text/javascript">



</script>

<div  class="commonPopupContainerDiv" style="display:block;">

</div>
<div id="popup_box" class="commonPopupBox"></div>
<style>

    #popup_box {
        display:none; 
    }
    .userEditOptionsPopup{
        display:none; 
    }
</style> 


